name: Restaurant Service CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, linux, x64, quickbite-ci]
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Java JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build
